# -*- coding: utf-8 -*-
"""customer_retail .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHXiloDiS2RCcEI_QpQ4BXaRrrM4N7En
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

df=pd.read_csv("/content/customer_retail .csv")

print(df.head())

df.info()

df=df.dropna()

df=df[['Quantity','UnitPrice','Country']]

encoder=LabelEncoder()
df['Country_encoded']=encoder.fit_transform(df['Country'])

plt.figure(figsize=(8,5))
plt.scatter(df['Quantity'],df['UnitPrice'])
plt.xlabel('quantity')
plt.ylabel('unit price')
plt.title('scatter plot of quantity vs unit price')
plt.show()

x=df[['Quantity','UnitPrice']]
y=df['Country_encoded']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

print("logistic regression")
log_model=LogisticRegression()
log_model.fit(x_train,y_train)
y_pred=log_model.predict(x_test)
accuracy_log=accuracy_score(y_test,y_pred)
print('accuracy:',accuracy_log)
cm=confusion_matrix(y_test,y_pred)
print('confusion matrix:')
print(cm)

print('Decision tree')
dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
y_pred=dt_model.predict(x_test)
accuracy_dt=accuracy_score(y_test,y_pred)
print('accuracy:',accuracy_dt)
print(confusion_matrix(y_test,y_pred))

print('KNN')
knn_model=KNeighborsClassifier()
knn_model.fit(x_train,y_train)
y_pred=knn_model.predict(x_test)
accuracy_k=accuracy_score(y_test,y_pred)
print('accuracy:',accuracy_k)
print(confusion_matrix(y_test,y_pred))

models=['logistic regression', 'decision tree', 'knn']
accuracy=[
    accuracy_log,
    accuracy_dt,
    accuracy_k
]
plt.figure(figsize=(10, 6))
plt.bar(models, accuracy, color=['b', 'r', 'g'])
plt.title('Model Accuracy Comparison')
plt.xlabel('Models')
plt.ylabel('Accuracy')
plt.show()